INSERT [dbo].[TaskSegmentHandCameraMapping] (TaskId, SegmentId, HandId, CameraId, Definition, ViewType) 
  VALUES
(1 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(1 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(1 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(1 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(1 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(1 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(1 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(1 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(2 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(2 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(2 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(2 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(2 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(2 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(2 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(2 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(3 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(3 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(3 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(3 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(3 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(3 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(3 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(3 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(4 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(4 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(4 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(4 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(4 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(4 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(4 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(4 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(5 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(5 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(5 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(5 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(5 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(5 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(5 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(5 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(6 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(6 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(6 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(6 , 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(6 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(6 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(6 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(6 , 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(7 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(7 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(7 , 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(7 , 6, 1, 1,'starts after forearm supination when object begins descend towards  table, ends just before placement on table ','Contralteral'), 
(7 , 5, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(7 , 4, 1, 4,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Ipsilateral'), 
(7 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(7 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(7 , 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(7 , 6, 2, 4,'starts after forearm supination when object begins descend towards  table, ends just before placement on table ','Contralteral'), 
(7 , 5, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(7 , 4, 2, 1,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Ipsilateral'), 
(8 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(8 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(8 , 3, 1, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(8 , 4, 1, 1,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(8 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(8 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(8 , 3, 2, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(8 , 4, 2, 4,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(9 , 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(9 , 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(9 , 3, 1, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(9 , 4, 1, 1,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(9 , 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(9 , 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(9 , 3, 2, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(9 , 4, 2, 4,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(10, 1, 1, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(10, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(10, 3, 1, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(10, 4, 1, 1,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(10, 1, 2, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Ipsilateral'), 
(10, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(10, 3, 2, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Contralteral'), 
(10, 4, 2, 4,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Contralteral'), 
(11, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(11, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(11, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(11, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(11, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(11, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(11, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(11, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(12, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(12, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(12, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(12, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(12, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(12, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(12, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(12, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(13, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(13, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(13, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(13, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(13, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(13, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(13, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(13, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(14, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(14, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(14, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(14, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(14, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(14, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(14, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(14, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(15, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(15, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(15, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(15, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(15, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(15, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(15, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(15, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(16, 1, 1, 1,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(16, 2, 1, 1,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(16, 3, 1, 4,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(16, 4, 1, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(16, 1, 2, 4,'Starts when patient demonstrates any movement of UE/trunk, ends just before grasp of object','Contralteral'), 
(16, 2, 2, 4,'starts when patient touches or attempts to grasp object, ends just before object begins to lift off table ','Contralteral'), 
(16, 3, 2, 1,'starts when object begins to lift off table, end just before object is placed on shelf ','Ipsilateral'), 
(16, 4, 2, 3,'starts just before object is placed on shelf and ends when hand begins the return towards the table','Transverse'), 
(17, 7, 1, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(17, 9, 1, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back'), 
(17, 7, 2, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(17, 9, 2, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back'), 
(18, 7, 1, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(18, 9, 1, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back'), 
(18, 7, 2, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(18, 9, 2, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back'), 
(19, 7, 1, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(19, 9, 1, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back'), 
(19, 7, 2, 2,'Starts when patient demonstrates any movement of UE/trunk, progressing to lifting arm towards head/mouth, ends just before hand gets to target (back/top of head, mouth).','Back'), 
(19, 9, 2, 2,'stars just before hand is placed on target (back/top of head, mouth), ends when the hand meets the target','Back')